//定义常量
const INCREASE = "INCREASE";
const DECREASE = "DECREASE";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

const ADDSTUDENT = "ADDSTUDENT"
const DELSTUDENT = "DELSTUDENT"

export {
    INCREASE,
    DECREASE,
    FETCH_USER_SUCCESS,
    ADDSTUDENT,
    DELSTUDENT
}